services:

  scraper:
    build: .
    container_name: scraper-cron-container
    restart: always
    env_file:
      - scraper/app/.env
    depends_on:
      - db
      - redis
    volumes:
      - ./logs:/var/log
    networks:
      - scraper-net

  celery-worker:
    build: .
    container_name: scraper-celery-worker
    restart: always
    command: ["celery", "-A", "scraper.app.workers", "worker", "--loglevel=info"]
    env_file:
      - scraper/app/.env
    depends_on:
      - redis
      - db
    networks:
      - scraper-net

  db:
    image: postgres:15
    container_name: scraper-db
    restart: always
    environment:
      POSTGRES_DB: carstest
      POSTGRES_USER: scraper_agentD7Apd9MCSf3C
      POSTGRES_PASSWORD: scraper_pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - scraper-net

  redis:
    image: redis:7
    container_name: scraper-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - scraper-net

volumes:
  db_data:
  redis_data:

networks:
  scraper-net:
    driver: bridge